apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      env: prod

images:
  - name: mablinov2704/frontend
    newTag: "1.0.0"
  - name: mablinov2704/bff
    newTag: "1.0.0"
  - name: mablinov2704/user-service
    newTag: "1.0.0"
  - name: mablinov2704/message-service
    newTag: "1.0.0"

patches:
  - path: patches/replicas-and-resources.yaml
  - path: patches/ingress-host.yaml
  - path: patches/message-affinity.yaml
